.PHONY: clean All

All:
	@echo "----------Building project:[ Laba1 - Debug ]----------"
	@"$(MAKE)" -f  "Laba1.mk"
clean:
	@echo "----------Cleaning project:[ Laba1 - Debug ]----------"
	@"$(MAKE)" -f  "Laba1.mk" clean
