.PHONY: clean All

All:
	@echo "----------Building project:[ Laba1.1 - Debug ]----------"
	@"$(MAKE)" -f  "Laba1.1.mk"
clean:
	@echo "----------Cleaning project:[ Laba1.1 - Debug ]----------"
	@"$(MAKE)" -f  "Laba1.1.mk" clean
